
# frozen_string_literal: true

source "https://rubygems.org"
brigth_coders = "Brightcoders-Bootcamps"
repo_name = "#{brigth_coders}/kata-07-pacman-team02-kata07.git"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rspec"
gem 'rake'
gem 'rubycritic'
gem 'rubycritic-small-badge', :require => false
gem 'sandi_meter'
gem 'rubocop', '~> 1.8', require: false